# Generated by Django 5.1.1 on 2026-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oily", models.FloatField(verbose_name="지성")),
                ("dry", models.FloatField(verbose_name="건성")),
                ("normal", models.FloatField(verbose_name="중성")),
                ("combination", models.FloatField(verbose_name="복합성")),
                ("sensitive", models.FloatField(verbose_name="민감성")),
                ("acne", models.FloatField(verbose_name="여드름")),
                ("atopy", models.FloatField(verbose_name="아토피")),
                ("teens", models.FloatField(verbose_name="10대")),
                ("twenties", models.FloatField(verbose_name="20대")),
                ("thirties", models.FloatField(verbose_name="30대")),
                ("forties_above", models.FloatField(verbose_name="40대 이상")),
                ("moisture_supply", models.FloatField(verbose_name="보습_수분_공급")),
                ("pore_care", models.FloatField(verbose_name="모공관리관련")),
                ("pigmentation_care", models.FloatField(verbose_name="색소침착관리")),
                ("lip_dry_care", models.FloatField(verbose_name="입술건조관리")),
            ],
        ),
        migrations.CreateModel(
            name="ProductInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="브랜드")),
                ("title", models.CharField(max_length=255, verbose_name="제품명")),
                ("discount", models.IntegerField(verbose_name="할인율")),
                ("price", models.IntegerField(verbose_name="가격")),
                (
                    "etc",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="기타 정보"
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="카테고리")),
                ("logo", models.URLField(max_length=500, verbose_name="로고 URL")),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="User ID"
                    ),
                ),
                ("atopy_level", models.FloatField(verbose_name="아토피 정도")),
                ("acne_level", models.FloatField(verbose_name="여드름 정도")),
                ("sensitivity_level", models.FloatField(verbose_name="민감성 정도")),
            ],
        ),
    ]
