# Generated by Django 5.1.1 on 2026-05-06 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "forehead_pigmentation_prediction",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "forehead_pigmentation_probabilities",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "left_cheek_pore_prediction",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "left_cheek_pore_probabilities",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "right_cheek_pore_prediction",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "right_cheek_pore_probabilities",
                    models.JSONField(blank=True, null=True),
                ),
                ("skin_type_prediction", models.IntegerField(blank=True, null=True)),
                ("skin_type_probabilities", models.JSONField(blank=True, null=True)),
                (
                    "forehead_moisture_prediction",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "forehead_moisture_probabilities",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "left_cheek_moisture_prediction",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "left_cheek_moisture_probabilities",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "right_cheek_moisture_prediction",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "right_cheek_moisture_probabilities",
                    models.JSONField(blank=True, null=True),
                ),
                ("lips_dryness_prediction", models.IntegerField(blank=True, null=True)),
                ("lips_dryness_probabilities", models.JSONField(blank=True, null=True)),
                (
                    "marked_image_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
